"""
app/models/plan.py — ImprovementTask ORM model.

Generated by the plan_generator service after an assessment completes.
Tasks are personalized to the user's observed weaknesses and gap analysis.

Graphiti: User -[HAS_GAP]-> Competency (severity, evidence context)
"""
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class ImprovementTask(Base):
    __tablename__ = "improvement_tasks"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    competency_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("competencies.id", ondelete="RESTRICT"), nullable=False
    )
    # Session that generated this task
    session_id: Mapped[str | None] = mapped_column(
        String(64), ForeignKey("assessment_sessions.id", ondelete="SET NULL"), nullable=True
    )

    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # The specific weakness observed in the assessment
    observed_weakness: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # Human-readable estimated time (e.g., "3 hours")
    estimated_time: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    # priority: high | medium | low
    priority: Mapped[str] = mapped_column(String(8), nullable=False, default="medium")

    # Success criteria checklist
    success_criteria: Mapped[list[str]] = mapped_column(ARRAY(String), nullable=False, default=list)

    # Completion tracking
    completed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user: Mapped["User"] = relationship(back_populates="improvement_tasks")  # type: ignore[name-defined]

    def __repr__(self) -> str:
        return f"<ImprovementTask id={self.id} competency={self.competency_id} priority={self.priority}>"
