/**
 * voiceService.ts — Frontend voice playback & TTS client.
 *
 * Primary: Streams ElevenLabs audio from FastAPI backend (POST /api/voice/tts).
 * Fallback: Uses browser SpeechSynthesis API if ElevenLabs API key is unconfigured.
 *
 * Provider-agnostic: Frontend plays the incoming audio without needing to know
 * API keys or provider details.
 */
import { apiClient, DATA_MODE } from '../lib/api';

class FrontendVoiceService {
  private activeAudio: HTMLAudioElement | null = null;

  /**
   * Speaks the provided text out loud.
   * Resolves only when speech playback has fully completed.
   */
  async speak(text: string): Promise<void> {
    this.stop();

    const cleanText = text.trim();
    if (!cleanText) return;

    if (DATA_MODE === 'api') {
      try {
        // Request audio from backend ElevenLabs TTS endpoint
        const res = await apiClient.post<Blob>('/api/voice/tts', { text: cleanText }, {
          responseType: 'blob',
          timeout: 15000,
        });

        if (res.data && res.data.size > 0) {
          await this.playAudioBlob(res.data);
          return;
        }
      } catch (err) {
        console.warn('Backend ElevenLabs audio stream unavailable, using browser TTS fallback:', err);
      }
    }

    // Client-side fallback: Web Speech Synthesis
    await this.speakBrowserFallback(cleanText);
  }

  /**
   * Plays an audio blob generated by ElevenLabs.
   */
  private playAudioBlob(blob: Blob): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      this.activeAudio = audio;

      audio.onended = () => {
        URL.revokeObjectURL(url);
        this.activeAudio = null;
        resolve();
      };

      audio.onerror = () => {
        URL.revokeObjectURL(url);
        this.activeAudio = null;
        reject(new Error('Audio playback failed'));
      };

      audio.play().catch((err) => {
        URL.revokeObjectURL(url);
        this.activeAudio = null;
        // Autoplay restrictions or user gesture requirements
        console.warn('Audio play() interrupted or blocked by browser policy:', err);
        resolve(); // Continue without blocking the interview state machine
      });
    });
  }

  /**
   * Browser SpeechSynthesis fallback when backend ElevenLabs is offline.
   */
  private speakBrowserFallback(text: string): Promise<void> {
    return new Promise<void>((resolve) => {
      if (!('speechSynthesis' in window)) {
        console.warn('Browser does not support SpeechSynthesis');
        resolve();
        return;
      }

      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = 'en-US';
      utterance.rate = 1.0;
      utterance.pitch = 1.0;

      utterance.onend = () => {
        resolve();
      };

      utterance.onerror = (e) => {
        console.warn('SpeechSynthesis error:', e);
        resolve();
      };

      window.speechSynthesis.speak(utterance);
    });
  }

  /**
   * Immediately stops any currently playing audio or speech synthesis.
   */
  stop(): void {
    if (this.activeAudio) {
      this.activeAudio.pause();
      this.activeAudio = null;
    }
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
  }
}

export const voiceService = new FrontendVoiceService();
