"""
app/routers/voice.py — Text-to-speech voice streaming endpoint.

POST /api/voice/tts
GET  /api/voice/status
"""
from typing import Optional
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.services.voice_service import voice_service

router = APIRouter(prefix="/api/voice", tags=["voice"])


class TTSRequest(BaseModel):
    text: str
    voice_id: Optional[str] = None


class VoiceStatusResponse(BaseModel):
    provider: str
    available: bool
    voice_id: str


@router.get("/status", response_model=VoiceStatusResponse)
async def get_voice_status() -> VoiceStatusResponse:
    """Returns whether the ElevenLabs voice service is active and configured."""
    return VoiceStatusResponse(
        provider="elevenlabs",
        available=voice_service.is_available(),
        voice_id=getattr(voice_service, "default_voice_id", "21m00Tcm4TlvDq8ikWAM"),
    )


@router.post("/tts")
async def generate_speech(body: TTSRequest):
    """
    Streams audio/mpeg bytes generated by ElevenLabs for the provided text.
    The frontend plays this stream directly for low-latency question audio.
    """
    if not body.text.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Text cannot be empty",
        )

    if not voice_service.is_available():
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="ElevenLabs TTS service is not configured. Set ELEVENLABS_API_KEY in backend environment.",
        )

    try:
        audio_stream = voice_service.generate_speech_stream(
            text=body.text,
            voice_id=body.voice_id,
        )
        return StreamingResponse(
            audio_stream,
            media_type="audio/mpeg",
            headers={
                "Cache-Control": "no-cache",
                "Content-Disposition": "inline; filename=question.mp3",
            },
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Voice synthesis error: {str(e)}",
        )
